print("Informe os dados da sua data de nascimento")
dia = input("Informe o dia: ")
mes = input("Informe o mes: ")
ano = input("Informe o ano: ")
print("Sua data de nascimento eh : " + dia + "/" + mes + "/" + ano)
print("Sua data de nascimento eh: ", dia, "/", mes, "/", ano)